// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaM3xR8yp00D28loWUs_gVPW1pEJ1pMR8',
    appId: '1:540028436000:web:ecc93741490c77b6660645',
    messagingSenderId: '540028436000',
    projectId: 'notebookstudy-1a2a0',
    authDomain: 'notebookstudy-1a2a0.firebaseapp.com',
    storageBucket: 'notebookstudy-1a2a0.appspot.com',
    measurementId: 'G-693X490JXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR3WLNTgwJkotVo-pMJ1xWKYbMoI1R8bQ',
    appId: '1:540028436000:android:e61691f06a960aae660645',
    messagingSenderId: '540028436000',
    projectId: 'notebookstudy-1a2a0',
    storageBucket: 'notebookstudy-1a2a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp-lza3dQsbg6A9opLptHB6GomepqzbEc',
    appId: '1:540028436000:ios:934b4e70c1d74a38660645',
    messagingSenderId: '540028436000',
    projectId: 'notebookstudy-1a2a0',
    storageBucket: 'notebookstudy-1a2a0.appspot.com',
    iosBundleId: 'com.example.notebookStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp-lza3dQsbg6A9opLptHB6GomepqzbEc',
    appId: '1:540028436000:ios:934b4e70c1d74a38660645',
    messagingSenderId: '540028436000',
    projectId: 'notebookstudy-1a2a0',
    storageBucket: 'notebookstudy-1a2a0.appspot.com',
    iosBundleId: 'com.example.notebookStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaM3xR8yp00D28loWUs_gVPW1pEJ1pMR8',
    appId: '1:540028436000:web:f5079dba60368476660645',
    messagingSenderId: '540028436000',
    projectId: 'notebookstudy-1a2a0',
    authDomain: 'notebookstudy-1a2a0.firebaseapp.com',
    storageBucket: 'notebookstudy-1a2a0.appspot.com',
    measurementId: 'G-7L7ZJBQ8TZ',
  );
}
